swagger: "2.0"

info:
  version: "1.0.0"

basePath: /

schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /greeting:
    get:
      description: Displays greetings
      operationId: greeting-handler
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GreetingResponse"
      #security:
      #  - api_key: []

definitions:
  GreetingResponse:
    required:
      - message
    properties:
      message:
        type: string

#securityDefinitions:
#  api_key:
#    type: apiKey
#    name: x-api-key
#    in: header
